// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-DbUKKSnA6-rWi9rKgAbPqzpQtL9A8FU',
    appId: '1:373769746419:android:524970b01f1852771d4486',
    messagingSenderId: '373769746419',
    projectId: 'virtucam-production',
    storageBucket: 'virtucam-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADQ7ZT8q-Dz-gwk3_Dtp-TjBqEHTgn6aQ',
    appId: '1:373769746419:ios:b29344636c78e28a1d4486',
    messagingSenderId: '373769746419',
    projectId: 'virtucam-production',
    storageBucket: 'virtucam-production.firebasestorage.app',
    iosBundleId: 'com.example.virtuacam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADQ7ZT8q-Dz-gwk3_Dtp-TjBqEHTgn6aQ',
    appId: '1:373769746419:ios:b29344636c78e28a1d4486',
    messagingSenderId: '373769746419',
    projectId: 'virtucam-production',
    storageBucket: 'virtucam-production.firebasestorage.app',
    iosBundleId: 'com.example.virtuacam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkGk59-uguQF-5-CUPxIzLHTcJqhG5V-U',
    appId: '1:373769746419:web:3f7b42d83540e0161d4486',
    messagingSenderId: '373769746419',
    projectId: 'virtucam-production',
    authDomain: 'virtucam-production.firebaseapp.com',
    storageBucket: 'virtucam-production.firebasestorage.app',
  );
}
